language: go
env:
  - GO111MODULE=on
  - GOFLAGS='-mod vendor'
go:
  - '1.11'
  - '1.12'
  - '1.13'
before_install:
  - go mod tidy
script:
  - go test ./... -v -cpu 2 -race -cover -coverprofile=coverage.txt -covermode=atomic
after_success:
  - bash <(curl -s https://codecov.io/bash)