language: go
go:
  - '1.8'
  - '1.9'
  - '1.10'
  - '1.11'
before_install:
  - go mod tidy
script:
  - go test ./... -v -cpu 2 -race -cover -coverprofile=coverage.txt -covermode=atomic
after_success:
  - bash <(curl -s https://codecov.io/bash)